os: 
  - Visual Studio 2017
  - Visual Studio 2015
  - Visual Studio 2013

platform:
  - Win32
  - Win64

before_build:
  - ps: Invoke-Command -ScriptBlock ([ScriptBlock]::Create((Invoke-Webrequest "https://raw.githubusercontent.com/tboox/xmake/dev/scripts/get.ps1" -UseBasicParsing).Content)) -ArgumentList "dev"
  - cmd: xmake --version

build_script:
  - cmd: xmake l scripts/test.lua -D

